### ISSUE TITLE
[enhancement] Reverse list direction & syntax suggestion

### ISSUE THREAD

**Issue by JustCryen** [AUNaseef/protonup#22]
The list command lists the newest version at the top of the list, which might sound fine at first but since we are in the terminal, output scrolls and only the oldest available versions are visible.
Reversing the direction would mean that whe newest version is right where we're about to type next.

One more thing, `-t` for "install" is quite unintuitive and `-i` is not used anywhere, why is it like this?
I would recommend switching `-t`,and `--tag` for `-i` and `--install` as install syntax.
Eventually `-S` just as arch does it.

In case of remove, `-r` is fine but I would replace `--rem` with full `--remove`

**Comment by AUNaseef** [comment]
The --releases output should reversed now, thanks for the suggestion. and yes, --remove makes sense, changed!

in order to install the latest version, you just run `protonup` so `-t` meaning tag makes more sense to me, `-i` won't mean anything by itself. Ideally it should be `protonup [tag]` without any flags but that would make things more complicated.
